version: "3"
services:
  client:
    image: boxer-client
    build:
      context: .
    ports:
     - 8080:8080
    volumes:
      - .:/boxer
    depends_on:
      - redis
      - mongodb
      - queue-server
    environment:
      - REDIS_HOST=redis
      - MONGO_HOST=mongodb
      - ZMQ_REP_HOST=queue-server
      - PYTHONPATH=/boxer
    command: sh ./prerun.sh client/run.py
    networks:
      - boxer_net

  websocket:
    image: boxer-websocket
    build:
      context: .
    ports:
     - 9999:9999
    volumes:
      - .:/boxer
    depends_on:
      - redis
      - mongodb
    environment:
      - REDIS_HOST=redis
      - MONGO_HOST=mongodb
      - PYTHONPATH=/boxer
    command: sh ./prerun.sh server/websocket.py
    networks:
      - boxer_net

  queue-server:
    image: boxer-queue-server
    build:
      context: .
    volumes:
      - .:/boxer
    depends_on:
      - redis
      - mongodb
    environment:
      - REDIS_HOST=redis
      - MONGO_HOST=mongodb
      - PYTHONPATH=/boxer
    command: sh ./prerun.sh server/queue_server.py
    networks:
      - boxer_net

  redis:
    image: redis:alpine
    networks:
      - boxer_net

  mongodb:
    image: mongo:3.2
    networks:
      - boxer_net
    environment:
      - MONGO_URL=mongodb://mongodb:27017/

networks:
  boxer_net:
